describe("insert mode", function()
  it("digraphs should work", function()
    local co = coroutine.running()
    local function pass(t)
      vim.defer_fn(function()
        coroutine.resume(co)
      end, t)
    end

    vim.cmd("new")
    pass(10)
    coroutine.yield()
    pass(10)
    vim.api.nvim_input("i<c-k>Hr<c-k>3_<esc>")
    coroutine.yield()
    local line = vim.api.nvim_buf_get_lines(0, 0, 1, true)
    assert.are.same({"₴…"}, line)
    vim.cmd("q!")
    pass(10)
    coroutine.yield()
  end)
end)
